package com.canaryos.shield

import org.json.JSONArray
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Before
import org.junit.Test
import java.io.InputStreamReader
import java.nio.charset.StandardCharsets

/**
 * Tokenizer parity test: validates that the Kotlin BertTokenizer produces
 * identical token IDs to the JS TextTokenizer.ts for all 20 test strings.
 *
 * The expected output fixture was generated by:
 *   npx tsx scripts/dump-tokenizer-output.ts > .../tokenizer_expected.json
 */
class BertTokenizerTest {

    private lateinit var tokenizer: BertTokenizer
    private lateinit var testCases: List<TestCase>

    data class TestCase(
        val text: String,
        val expectedInputIds: IntArray,
        val expectedAttentionMask: IntArray
    )

    @Before
    fun setUp() {
        // Load vocab.txt from test resources
        val vocabStream = javaClass.classLoader!!.getResourceAsStream("vocab.txt")
        assertNotNull("vocab.txt must be in test resources", vocabStream)

        val vocab = mutableMapOf<String, Int>()
        InputStreamReader(vocabStream!!, StandardCharsets.UTF_8).useLines { lines ->
            lines.forEachIndexed { index, line ->
                val token = line.trim()
                if (token.isNotEmpty()) {
                    vocab[token] = index
                }
            }
        }
        tokenizer = BertTokenizer.fromVocabMap(vocab)

        // Load expected output fixture
        val fixtureStream = javaClass.classLoader!!.getResourceAsStream("tokenizer_expected.json")
        assertNotNull("tokenizer_expected.json must be in test resources", fixtureStream)

        val fixtureJson = InputStreamReader(fixtureStream!!, StandardCharsets.UTF_8).readText()
        val jsonArray = JSONArray(fixtureJson)

        testCases = (0 until jsonArray.length()).map { i ->
            val obj = jsonArray.getJSONObject(i)
            val text = obj.getString("text")
            val inputIdsArr = obj.getJSONArray("inputIds")
            val attMaskArr = obj.getJSONArray("attentionMask")

            TestCase(
                text = text,
                expectedInputIds = IntArray(inputIdsArr.length()) { j -> inputIdsArr.getInt(j) },
                expectedAttentionMask = IntArray(attMaskArr.length()) { j -> attMaskArr.getInt(j) }
            )
        }
    }

    @Test
    fun `vocab loaded with expected size`() {
        assertEquals("Vocab should have 30522 tokens", 30522, tokenizer.vocabSize)
    }

    @Test
    fun `all 20 test cases produce identical token IDs to JS`() {
        assertEquals("Expected 20 test cases in fixture", 20, testCases.size)

        for ((index, tc) in testCases.withIndex()) {
            val result = tokenizer.tokenize(tc.text, maxLength = 128)

            assertArrayEquals(
                "InputIds mismatch for test case $index: \"${tc.text.take(40)}\"",
                tc.expectedInputIds,
                result.inputIds
            )
            assertArrayEquals(
                "AttentionMask mismatch for test case $index: \"${tc.text.take(40)}\"",
                tc.expectedAttentionMask,
                result.attentionMask
            )
        }
    }

    @Test
    fun `empty string produces CLS SEP`() {
        val result = tokenizer.tokenize("", maxLength = 128)
        assertEquals(BertTokenizer.CLS_ID, result.inputIds[0])
        assertEquals(BertTokenizer.SEP_ID, result.inputIds[1])
        assertEquals(BertTokenizer.PAD_ID, result.inputIds[2])
        assertEquals(1, result.attentionMask[0])
        assertEquals(1, result.attentionMask[1])
        assertEquals(0, result.attentionMask[2])
        assertEquals(2, result.tokenCount)
    }

    @Test
    fun `output arrays always have maxLength size`() {
        val inputs = listOf("short", "a longer sentence with more words", "")
        for (input in inputs) {
            val result = tokenizer.tokenize(input, maxLength = 128)
            assertEquals("inputIds length", 128, result.inputIds.size)
            assertEquals("attentionMask length", 128, result.attentionMask.size)
        }
    }

    @Test
    fun `homoglyph detection identifies mixed scripts`() {
        // Cyrillic 'a' (U+0430) mixed with Latin
        assert(tokenizer.detectHomoglyphs("\u0430pple"))
        // Pure Latin
        assert(!tokenizer.detectHomoglyphs("apple"))
        // Zero-width character
        assert(tokenizer.detectHomoglyphs("ab\u200bcd"))
    }
}
